export const TUNING = {
  tileSize: 48,
  chunkWidth: 25,
  chunkHeight: 18,
  chunksAhead: 4,
  chunksBehind: 2,
  fixedStepSeconds: 1 / 60,
  maxFrameSeconds: 0.1,
  qSpeedTilesPerSecond: 1.58,
  perceptionRadius: 6,
  baseCommitmentSeconds: 2.25,
  intentionSwitchMargin: 9,
  hungerPerSecond: 0.0065,
  hungerTraitRate: 0.0055,
  hungryThreshold: 0.64,
  starvingThreshold: 0.84,
  naturalFoodRelief: 0.5,
  treatRelief: 0.62,
  callDurationSeconds: 2.4,
  careDurationSeconds: 6,
  carePauseSeconds: 0.72,
  strangeDurationSeconds: 8,
  obstructionDurationSeconds: 13,
  treatDurationSeconds: 15,
  rescueRadiusTiles: 4,
  cooldowns: {
    place: 7.5,
    treat: 5.5,
    call: 4.25,
    care: 6.5,
    rescue: 28,
  },
  actionKeys: {
    place: "1",
    treat: "2",
    call: "3",
    care: "4",
    rescue: "5",
  },
} as const;

export type TunableAction = keyof typeof TUNING.cooldowns;
